# Generated by Django 3.2.8 on 2021-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_imageforcustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='imageForCustomization',
            field=models.ImageField(blank=True, null=True, upload_to='Images/CustomizationImages/', verbose_name='Image For Customization'),
        ),
    ]
