# Generated by Django 3.2.8 on 2021-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_imageforcustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='imageForCustomization',
        ),
        migrations.AddField(
            model_name='order',
            name='imageForCustomization1',
            field=models.ImageField(blank=True, null=True, upload_to='Images/CustomizationImages/', verbose_name='Image For Customization 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='imageForCustomization2',
            field=models.ImageField(blank=True, null=True, upload_to='Images/CustomizationImages/', verbose_name='Image For Customization 2'),
        ),
    ]
